name: DENORTLUI
on:
  workflow_dispatch:
  project_card:
    type: [created, moved]
jobs:
  my_job:
    name: Actividad 12
    runs-on: ubuntu-latest
    steps:
      - name: Send mailer
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp-mail.outlook.com
          port: 587
          account: denis31599@hotmail.com
          password: ${{secrets.CREDS_CORREO_PWD}}
          sender: Denis
          from: denis31599@hotmail.com
          to: denis31599@hotmail.com
          subject: Notificacion del proyecto FS
          body: Se ha realizado una modificación en el proyecto <3
          
          
        
