name: DENORTLUI
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
jobs:
  my_job:
    name: Actividad 12
    runs-on: ubuntu-latest
    steps:
      - name: Send mailer
        uses: betterfor/action-send-mail@v0.1.1
        with:
          server_address: '	smtp.office365.com'
          server_port: 587
          username: 'denis31599@hotmail.com'
          password: ${{secrets.CREDS_CORREO_PWD}}
          subject: 'Notificacion del proyecto FS'
          to: 'denorltui@us.es'
          from: 'Denis<denis31599@hotmail.com>'
          body: 'Se ha realizado una modificación en el proyecto <3'
      - name: Mensaje de fin
        run: echo 'Correo enviado :)'
          
        
